from datetime import date
from unittest import mock

import pytest
from pydantic.types import NoneBytes

from calculation_engine.models.annual_summary import PreviewYearLoss
from calculation_engine.operation_classes import OperationClassesCommons
from calculation_engine.ticker_types import RealStateFunds, Stock


@pytest.fixture
def operation_classes_commons_instance():
    return OperationClassesCommons()


@pytest.fixture
def operations(finantial_normal_operation, finantial_day_trade_operation):
    finantial_day_trade_operation.date = date(2020, 11, 26)
    return [finantial_normal_operation, finantial_day_trade_operation]


def test_append_inconsistency(operation_classes_commons_instance):
    messages_to_append = ["message_1", "message_2", "message_1"]
    for message in messages_to_append:
        operation_classes_commons_instance.append_inconsistency(message)
    assert operation_classes_commons_instance.inconsistencies == ["message_1", "message_2"]


@mock.patch(
    "calculation_engine.operation_classes.operation_classes_commons.SimpleCappUtils.get_list_with_filters",
)
def test_agroup_operations_by_ticker_type(
    mock_get_list_with_filters, operation_classes_commons_instance, operations
):
    mock_get_list_with_filters.side_effect = [[operations[0]], [operations[1]], []]

    expected_agrouped_operations_by_ticker_type = {
        "fiis": [operations[0]],
        "stock": [operations[1]],
        "bdr": [],
    }

    assert (
        operation_classes_commons_instance.agroup_operations_by_ticker_type(operations)
        == expected_agrouped_operations_by_ticker_type
    )


def test_compile_year_months_reference_year(
    operation_classes_commons_instance, year_months_to_reference_year
):
    reference_year = 2020

    assert (
        operation_classes_commons_instance.compile_year_months_reference_year(reference_year)
        == year_months_to_reference_year
    )


@pytest.mark.parametrize(
    "previous_year_loss, summary_by_ticker, expected_summary_by_monthly, ticker_type_instance, operation_class",
    [
        (
            [],
            [
                {
                    "year_month": "01/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "02/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "03/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "04/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "05/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "06/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "07/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "08/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "09/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "10/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 5.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 641.24,
                    "total_amount_sale": 0,
                    "total_units_purchase": 5.0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0.04,
                    "result": 0,
                },
                {
                    "year_month": "11/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 1.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 515.07,
                    "total_units_purchase": 0,
                    "total_units_sale": 4.0,
                    "cgs": 512.992,
                    "irrf": 0,
                    "result": 2.078000000000088,
                },
                {
                    "year_month": "12/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 1.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
            ],
            [
                {
                    "year_month": "01/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "02/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "03/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "04/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "05/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "06/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "07/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "08/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "09/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "10/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0.04,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "11/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 515.07,
                    "ir_flag": True,
                    "result": 2.078000000000088,
                    "irrf": 0,
                    "ir_to_pay": 0.4156000000000177,
                    "final_result": 1.6624000000000705,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "12/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
            ],
            RealStateFunds,
            "normal",
        ),
        (
            [
                PreviewYearLoss(
                    **{
                        "year_month": "12/2019",
                        "ticker_type": "fiis",
                        "operation_class": "normal",
                        "accumulated_loss": -10,
                    }
                )
            ],
            [
                {
                    "year_month": "01/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "02/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "03/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "04/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "05/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "06/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "07/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "08/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "09/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "10/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 5.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 641.24,
                    "total_amount_sale": 0,
                    "total_units_purchase": 5.0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0.04,
                    "result": 0,
                },
                {
                    "year_month": "11/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 1.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 515.07,
                    "total_units_purchase": 0,
                    "total_units_sale": 4.0,
                    "cgs": 512.992,
                    "irrf": 0,
                    "result": 2.078000000000088,
                },
                {
                    "year_month": "12/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 1.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
            ],
            [
                {
                    "year_month": "01/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "02/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "03/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "04/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "05/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "06/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "07/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "08/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "09/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "10/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0.04,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "11/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 515.07,
                    "ir_flag": True,
                    "result": 2.078000000000088,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 2.078000000000088,
                    "accumulated_loss": -7.92199999999912,
                },
                {
                    "year_month": "12/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -7.92199999999912,
                },
            ],
            RealStateFunds,
            "normal",
        ),
        (
            [
                PreviewYearLoss(
                    **{
                        "year_month": "12/2019",
                        "ticker_type": "fiis",
                        "operation_class": "normal",
                        "accumulated_loss": -10,
                    }
                )
            ],
            [
                {
                    "year_month": "01/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "02/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "03/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "04/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "05/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "06/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "07/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "08/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "09/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "10/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 5.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 641.24,
                    "total_amount_sale": 0,
                    "total_units_purchase": 5.0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0.04,
                    "result": 0,
                },
                {
                    "year_month": "11/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 1.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 525,
                    "total_units_purchase": 0,
                    "total_units_sale": 4.0,
                    "cgs": 512.992,
                    "irrf": 0,
                    "result": 12.008,
                },
                {
                    "year_month": "12/2020",
                    "broker": None,
                    "ticker_type": "fiis",
                    "ticker": "XPLG11",
                    "operation_class": "normal",
                    "position": 1.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
            ],
            [
                {
                    "year_month": "01/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "02/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "03/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "04/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "05/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "06/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "07/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "08/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "09/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "10/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0.04,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "11/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 525,
                    "ir_flag": True,
                    "result": 12.008,
                    "irrf": 0,
                    "ir_to_pay": 0.4016,
                    "final_result": 11.6064,
                    "accumulated_loss": 0,
                },
                {
                    "year_month": "12/2020",
                    "ticker_type": "fiis",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": 0,
                },
            ],
            RealStateFunds,
            "normal",
        ),
        (
            [
                PreviewYearLoss(
                    **{
                        "year_month": "12/2019",
                        "ticker_type": "stock",
                        "operation_class": "normal",
                        "accumulated_loss": -10,
                    }
                )
            ],
            [
                {
                    "year_month": "01/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "02/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "03/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "04/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "05/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "06/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "07/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "08/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "09/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "10/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 5.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 641.24,
                    "total_amount_sale": 0,
                    "total_units_purchase": 5.0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0.04,
                    "result": 0,
                },
                {
                    "year_month": "11/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 1.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 525,
                    "total_units_purchase": 0,
                    "total_units_sale": 4.0,
                    "cgs": 512.992,
                    "irrf": 0,
                    "result": 12.008,
                },
                {
                    "year_month": "12/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 1.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
            ],
            [
                {
                    "year_month": "01/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": False,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "02/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": False,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "03/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": False,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "04/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": False,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "05/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": False,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "06/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": False,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "07/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": False,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "08/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": False,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "09/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": False,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "10/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": False,
                    "result": 0,
                    "irrf": 0.04,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "11/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 525,
                    "ir_flag": False,
                    "result": 12.008,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 12.008,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "12/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": False,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
            ],
            Stock,
            "normal",
        ),
        (
            [
                PreviewYearLoss(
                    **{
                        "year_month": "12/2019",
                        "ticker_type": "stock",
                        "operation_class": "normal",
                        "accumulated_loss": -1000,
                    }
                )
            ],
            [
                {
                    "year_month": "01/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "02/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "03/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "04/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "05/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "06/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "07/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "08/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "09/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 0.0,
                    "average_purchase_price": 0.0,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
                {
                    "year_month": "10/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 200.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 25649.6,
                    "total_amount_sale": 0,
                    "total_units_purchase": 200.0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0.04,
                    "result": 0,
                },
                {
                    "year_month": "11/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 50.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 30000,
                    "total_units_purchase": 0,
                    "total_units_sale": 150,
                    "cgs": 19237.20,
                    "irrf": 0,
                    "result": 10762.8,
                },
                {
                    "year_month": "12/2020",
                    "broker": None,
                    "ticker_type": "stock",
                    "ticker": "KGBRUSSIA",
                    "operation_class": "normal",
                    "position": 50.0,
                    "average_purchase_price": 128.248,
                    "total_amount_purchase": 0,
                    "total_amount_sale": 0,
                    "total_units_purchase": 0,
                    "total_units_sale": 0,
                    "cgs": 0,
                    "irrf": 0,
                    "result": 0,
                },
            ],
            [
                {
                    "year_month": "01/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "02/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "03/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "04/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "05/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "06/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "07/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "08/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "09/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "10/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0.04,
                    "ir_to_pay": 0,
                    "final_result": 0,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "11/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 30000,
                    "ir_flag": True,
                    "result": 10762.8,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 12.008,
                    "accumulated_loss": -10,
                },
                {
                    "year_month": "12/2020",
                    "ticker_type": "stock",
                    "operation_class": "normal",
                    "total_amount_sale": 0,
                    "ir_flag": True,
                    "result": 0,
                    "irrf": 0,
                    "ir_to_pay": 0,
                    "final_result": 1152.56,
                    "accumulated_loss": 0,
                },
            ],
            Stock,
            "normal",
        ),
    ],
    ids=[
        "fiis_operations_without_previous_year_loss",
        "fiis_operations_with_previous_year_loss_result_less_loss",
        "fiis_operations_with_previous_year_loss_result_greater_loss",
        "stock_operations_with_previous_year_loss_result_less_exception_sale_limit",
        "stock_operations_with_previous_year_loss_result_greater_exception_sale_limit",
    ],
)
@mock.patch(
    "calculation_engine.operation_classes.operation_classes_commons.SimpleCappUtils.unpack_dict_in_list_of_rows"
)
def test_calcule_operations_by_monthly(
    mock_unpack_dict_in_list_of_rows,
    previous_year_loss,
    summary_by_ticker,
    expected_summary_by_monthly,
    ticker_type_instance,
    operation_class,
    operation_classes_commons_instance,
    year_months_to_reference_year,
):
    reference_year = 2020

    mock_unpack_dict_in_list_of_rows.return_value = expected_summary_by_monthly

    setattr(operation_classes_commons_instance, "ticker_type_instance", ticker_type_instance())
    setattr(operation_classes_commons_instance, "operation_class", operation_class)

    assert operation_classes_commons_instance._calcule_operations_by_monthly(
        summary_by_ticker, reference_year, year_months_to_reference_year, previous_year_loss
    ) == {"summary_by_monthly": expected_summary_by_monthly}

    assert mock_unpack_dict_in_list_of_rows.call_count == 1


def test_calcule_operations(operation_classes_commons_instance, year_months_to_reference_year):
    operations = [1, 2]
    reference_year = 2020
    previous_year_loss = [3, 4]
    operation_classes_commons_instance.compile_year_months_reference_year = mock.Mock(
        return_value=year_months_to_reference_year
    )
    operation_classes_commons_instance._calcule_operations_by_ticker = mock.Mock(
        return_value={"summary_by_ticker": 1}
    )
    operation_classes_commons_instance._calcule_operations_by_monthly = mock.Mock(
        return_value={"summary_by_monthly": 2}
    )

    operation_classes_commons_instance.calcule_operations(operations, reference_year, previous_year_loss) == {
        "summary_by_ticker": 1,
        "summary_by_monthly": 2,
    }

    operation_classes_commons_instance.compile_year_months_reference_year.assert_called_once_with(
        reference_year
    )
    operation_classes_commons_instance._calcule_operations_by_ticker.assert_called_once_with(
        operations, reference_year, year_months_to_reference_year
    )
    operation_classes_commons_instance._calcule_operations_by_monthly.assert_called_once_with(
        1, 2020, year_months_to_reference_year, previous_year_loss,
    )


@pytest.mark.parametrize("operation_class, operations", [("day_trade", []), ("normal", [1, 2])])
@mock.patch("calculation_engine.operation_classes.operation_classes_commons.RealStateFunds.process")
@mock.patch("calculation_engine.operation_classes.operation_classes_commons.Stock.process")
def test_process(
    mock_process_real_state_funds,
    mock_process_stocks,
    operation_class,
    operations,
    operation_classes_commons_instance,
):
    reference_year = 2020
    previous_year_loss = []

    operation_classes_commons_instance.operation_class = mock.PropertyMock(return_value=operation_class)
    operation_classes_commons_instance._calcule_average_purchase_price_for_each_sale = mock.Mock(
        return_value={"average": 1}
    )
    operation_classes_commons_instance.calcule_operations = mock.Mock(return_vales="one_function")
    operation_classes_commons_instance.agroup_operations_by_ticker_type = mock.Mock(
        return_value={"fiis": [1, 2], "stock": [2, 3]}
    )
    mock_process_real_state_funds.return_value = {
        "summary_by_ticker": [1],
        "custody_by_ticker_and_reference_year": [2],
        "summary_by_monthly": [3],
    }
    mock_process_stocks.return_value = {
        "summary_by_ticker": [4],
        "custody_by_ticker_and_reference_year": [5],
        "summary_by_monthly": [6],
    }

    result = operation_classes_commons_instance.process(operations, reference_year, previous_year_loss)
    if not operations:
        assert result == {
            "summary_by_ticker": [],
            "custody_by_ticker_and_reference_year": [],
            "summary_by_monthly": [],
            "inconsistencies": []
        }
        return

    assert result == {
        "summary_by_ticker": [4, 1],
        "custody_by_ticker_and_reference_year": [5, 2],
        "summary_by_monthly": [6, 3],
        "inconsistencies": []
    }

